import pygame
import os

# --- Dimensões da Tela ---
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60

# --- Paleta de Cores Principal ---
COLOR_WHITE = (255, 255, 255)
COLOR_OFF_WHITE = (245, 245, 238)
COLOR_LIGHT_TEXT = (240, 240, 240)
COLOR_BLACK = (0, 0, 0)

# --- Cores do Tema Verde ---
COLOR_GREEN_DARK = (10, 50, 30)
COLOR_GREEN_MEDIUM = (20, 80, 50)
COLOR_GREEN_LIGHT = (30, 110, 70)
COLOR_GREEN_VERY_DARK_PANEL = (15, 40, 25, 220)

# Cores de Gradiente para Fundos
GRADIENT_GREEN_DARK_START = COLOR_GREEN_DARK
GRADIENT_GREEN_DARK_END = COLOR_GREEN_MEDIUM

# Cores de Acento e Texto Primárias
COLOR_GOLD_ACCENT = (204, 172, 90)
COLOR_LIGHT_GOLD_TEXT = (255, 238, 175)
COLOR_RED_HIGHLIGHT = (230, 60, 60)
COLOR_YELLOW_HIGHLIGHT = (255, 230, 120)

# Aliases para clareza
YELLOW_TEXT = COLOR_YELLOW_HIGHLIGHT
RED_TEXT = COLOR_RED_HIGHLIGHT

# Cores Específicas para UI (Fundos Gerais)
SCREEN_BACKGROUND_START_COLOR = GRADIENT_GREEN_DARK_START
SCREEN_BACKGROUND_END_COLOR = GRADIENT_GREEN_DARK_END
MENU_PANEL_COLOR = COLOR_GREEN_VERY_DARK_PANEL

# --- CORES ESPECÍFICAS PARA A TELA DE REGRAS ---
RULES_BACKGROUND_START_COLOR = COLOR_GREEN_DARK
RULES_BACKGROUND_END_COLOR = COLOR_GREEN_MEDIUM
RULES_MAIN_TITLE_COLOR = COLOR_LIGHT_GOLD_TEXT
RULES_SECTION_TITLE_COLOR = COLOR_GOLD_ACCENT
RULES_TEXT_BODY_COLOR = COLOR_OFF_WHITE
RULES_DIVIDER_LINE_COLOR = (60, 100, 80, 180)

# Cores PADRÃO para a classe Button
BUTTON_DEFAULT_BG_NORMAL = (70, 70, 170)
BUTTON_DEFAULT_BG_HOVER = (100, 100, 200)
BUTTON_DEFAULT_BG_DISABLED = (120, 120, 120)
BUTTON_DEFAULT_TEXT_NORMAL = COLOR_WHITE
BUTTON_DEFAULT_TEXT_DISABLED = (185, 185, 185)

# Cores Específicas para Botões do Menu
MENU_BUTTON_BG_NORMAL_COLOR = (80, 120, 90)
MENU_BUTTON_BG_HOVER_COLOR = (100, 150, 110)
MENU_BUTTON_TEXT_COLOR = COLOR_WHITE
MENU_BUTTON_BORDER_COLOR = COLOR_GOLD_ACCENT

# Cores Específicas para Botões de Jogo
GAME_BUTTON_BG_NORMAL_COLOR = (60, 100, 70)
GAME_BUTTON_BG_HOVER_COLOR = (80, 130, 90)
GAME_BUTTON_TEXT_COLOR = COLOR_LIGHT_TEXT

# Cores para Painel de Log
LOG_PANEL_BG_COLOR = (25, 35, 55, 235)
LOG_PANEL_BORDER_COLOR = COLOR_GOLD_ACCENT
LOG_TEXT_COLOR = COLOR_OFF_WHITE

# Placeholders de Cartas
CARD_PLACEHOLDER_BG = (200,200,200); CARD_BACK_PLACEHOLDER_BG = (40,40,120); CARD_OUTLINE_COLOR = COLOR_BLACK

# --- Fontes (Nomes de arquivo em assets/fonts/) ---
FONT_FILENAME_THEME_TITLE = "MedievalSharp-Regular.ttf"
FONT_FILENAME_BODY = None
FONT_FILENAME_HEADER = FONT_FILENAME_THEME_TITLE
FONT_FILENAME_SECTION_TITLE = FONT_FILENAME_THEME_TITLE

# --- Tamanhos de Fonte ---
FONT_SIZE_APP_TITLE = 68
FONT_SIZE_SCREEN_HEADER = 52 
FONT_SIZE_MENU_BUTTON = 40
FONT_SIZE_GAME_ACTION_BUTTON = 28
FONT_SIZE_RULES_SECTION_TITLE = 30 
FONT_SIZE_RULES_BODY = 20
FONT_SIZE_RULES_INTRO_TEXT = 26
FONT_SIZE_LOG_PANEL_TITLE = 32
FONT_SIZE_LOG_ROUND_TITLE = 28
FONT_SIZE_LOG_SUMMARY = 20
FONT_SIZE_LOG_DETAIL = 18
FONT_SIZE_GAME_STATUS = 28
FONT_SIZE_HAND_COUNT = 18
FONT_SIZE_PLAYER_NAME = 20

# --- Layout e Posições ---
UI_PANEL_BORDER_RADIUS = 15
UI_BUTTON_BORDER_RADIUS = 8

# Layout Tela de Regras - Constantes específicas para RulesScreen
RULES_PANEL_MARGIN_X = 50
RULES_PANEL_MARGIN_Y = 40
RULES_PANEL_BORDER_WIDTH = 4
RULES_PANEL_CONTENT_PADDING = 30
RULES_TEXT_SIDE_PADDING_INSIDE_PANEL = 25
RULES_SCROLLBAR_WIDTH = 18
RULES_SCROLLBAR_PADDING = 8
RULES_TITLE_Y_INSIDE_PANEL = RULES_PANEL_CONTENT_PADDING
RULES_TEXT_START_Y_INSIDE_PANEL = FONT_SIZE_SCREEN_HEADER + 4 + 25
RULES_SECTION_SPACING_AFTER = 28
RULES_PARAGRAPH_SPACING_AFTER = 15
RULES_LIST_ITEM_SPACING_AFTER = 10
RULES_LINE_SPACING_INTERNAL = 5
RULES_DIVIDER_MARGIN_Y = 20
RULES_BUTTON_Y_OFFSET_FROM_BOTTOM = 70 # Para o botão "Voltar ao Menu"

# Constantes de Cartas (usadas em vários lugares)
CARD_WIDTH=100; CARD_HEIGHT=140; CARD_SPACING=15

# Constantes de layout para exemplos de cartas nas Regras
RULES_EXAMPLE_CARD_SCALE = 0.60
RULES_EXAMPLE_CARD_WIDTH = int(CARD_WIDTH * RULES_EXAMPLE_CARD_SCALE)
RULES_EXAMPLE_CARD_HEIGHT = int(CARD_HEIGHT * RULES_EXAMPLE_CARD_SCALE)
RULES_EXAMPLE_CARD_SPACING_X = 8
RULES_EXAMPLE_CARD_MARGIN_Y = 20

# Layout Tela de Jogo
GREEN_TABLE_COLOR_FALLBACK = COLOR_GREEN_MEDIUM
TABLE_AREA_COLOR = (15, 60, 35, 180)
TABLE_AREA_BORDER_COLOR = COLOR_GOLD_ACCENT
CENTER_TABLE_RECT_WIDTH=CARD_WIDTH*2+CARD_SPACING*7; CENTER_TABLE_RECT_HEIGHT=CARD_HEIGHT+CARD_SPACING*4
CENTER_TABLE_RECT_X=(SCREEN_WIDTH-CENTER_TABLE_RECT_WIDTH)//2; CENTER_TABLE_RECT_Y=(SCREEN_HEIGHT-CENTER_TABLE_RECT_HEIGHT)//2-40
GAME_ACTION_BUTTON_WIDTH=210
GAME_ACTION_BUTTON_HEIGHT=45
GAME_ACTION_BUTTON_X=SCREEN_WIDTH-GAME_ACTION_BUTTON_WIDTH-25
GAME_ACTION_BUTTON_Y=SCREEN_HEIGHT-GAME_ACTION_BUTTON_HEIGHT-25
STATUS_MESSAGE_Y=CENTER_TABLE_RECT_Y+CENTER_TABLE_RECT_HEIGHT+45
DECK_OFFSET_X=70
PLAYER_DECK_POS=pygame.math.Vector2(DECK_OFFSET_X,SCREEN_HEIGHT-CARD_HEIGHT-40)
OPPONENT_DECK_POS=pygame.math.Vector2(DECK_OFFSET_X,40)
PLAYER_CARD_PLAY_POS=pygame.math.Vector2(CENTER_TABLE_RECT_X+(CENTER_TABLE_RECT_WIDTH*0.25)-CARD_WIDTH*0.5,CENTER_TABLE_RECT_Y+(CENTER_TABLE_RECT_HEIGHT-CARD_HEIGHT)//2)
OPPONENT_CARD_PLAY_POS=pygame.math.Vector2(CENTER_TABLE_RECT_X+(CENTER_TABLE_RECT_WIDTH*0.75)-CARD_WIDTH*0.5,CENTER_TABLE_RECT_Y+(CENTER_TABLE_RECT_HEIGHT-CARD_HEIGHT)//2)
WAR_BET_PLAYER_OFFSET_X=-(CARD_WIDTH*0.7); WAR_BET_OPPONENT_OFFSET_X=(CARD_WIDTH*0.7); WAR_BET_Y_OFFSET=CARD_HEIGHT*0.15
WIN_PILE_OFFSET_X=60
PLAYER_WIN_PILE_POS=pygame.math.Vector2(SCREEN_WIDTH-CARD_WIDTH-WIN_PILE_OFFSET_X,PLAYER_DECK_POS.y)
OPPONENT_WIN_PILE_POS=pygame.math.Vector2(SCREEN_WIDTH-CARD_WIDTH-WIN_PILE_OFFSET_X,OPPONENT_DECK_POS.y)

# Layout Log Display
LOG_PANEL_WIDTH=SCREEN_WIDTH*0.85; LOG_PANEL_HEIGHT=SCREEN_HEIGHT*0.80
LOG_PANEL_X=(SCREEN_WIDTH-LOG_PANEL_WIDTH)//2; LOG_PANEL_Y=(SCREEN_HEIGHT-LOG_PANEL_HEIGHT)//2
LOG_SCROLL_BAR_WIDTH=20
LOG_BUTTON_X=SCREEN_WIDTH-170; LOG_BUTTON_Y=20; LOG_BUTTON_WIDTH=150; LOG_BUTTON_HEIGHT=40

# Caminhos de Assets
_UI_MODULE_PATH_FOR_CONSTANTS = os.path.dirname(os.path.abspath(__file__))
ASSETS_BASE_PATH = os.path.join(_UI_MODULE_PATH_FOR_CONSTANTS, "assets")
CARD_ASSETS_PATH = os.path.join(ASSETS_BASE_PATH, "cards")
BACKGROUND_ASSETS_PATH = os.path.join(ASSETS_BASE_PATH, "backgrounds")
FONT_ASSETS_PATH = os.path.join(ASSETS_BASE_PATH, "fonts")

# Timers
UI_EVENT_BASE = pygame.USEREVENT + 100
UI_EVENT_REVEAL_CARDS_ON_TABLE = UI_EVENT_BASE + 1
UI_EVENT_ANIMATE_WINNER_COLLECTION = UI_EVENT_BASE + 2
UI_EVENT_CONTINUE_GAME_SEQUENCE = UI_EVENT_BASE + 3